const recSearches = [
  "iphone",
  "Fz v3 bikes",
  "Tata Cars",
  "Books",
  "Networking Jobs",
];
const newlistedCar = [
  "Mahindra & Mahindra",
  "Tata Motors",
  "Maruti Suzuki",
  "Hyundai",
  "Honda",
  "Toyota",
];
const newlistedBike = [
  "TVS Motor",
  "Bajaj Auto",
  "Royal Enfield",
  "Yamaha Motor Company",
  "KTM",
  "Royal Enfield",
];
const newcarDetail = [
  {
    price: "$ 3,75,000",
    eco: "82/100",
    km: "2014-75,000km",
    model: "Honda City 1.5 sv i-VTEC MT, 2013",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/Minicar.png",
  },
  {
    price: "$ 5,20,000",
    eco: "90/100",
    km: "2018-40,000km",
    model: "Hyundai Creta SX, 2018",
    location: "Mumbai",
    date: "Today",
    bannerImg: "/bmw.png",
  },
  {
    price: "$ 2,95,000",
    eco: "75/100",
    km: "2012-85,000km",
    model: "Maruti Suzuki Swift VDI, 2012",
    location: "Delhi",
    date: "Today",
    bannerImg: "/Fortuner.png",
  },
  {
    price: "$ 4,10,000",
    eco: "88/100",
    km: "22016-60,000km",
    model: "Tata Tiago XZ, 2016",
    location: "Chennai",
    date: "Today",
    bannerImg: "/bmw.png",
  },
];
const newbikeDetail = [
  {
    price: "$ 35,000",
    eco: "82/100",
    km: "2014-75,000km",
    model: "Honda Bike, 2013",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/hondabike.jpeg",
  },

  {
    price: "$ 86,000",
    eco: "87/100",
    km: "2014-4,000km",
    model: "Duke 200, bike",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/ktmbike.jpg",
  },
  {
    price: "$ 35,000",
    eco: "82/100",
    km: "2014-75,000km",
    model: "Honda Bike, 2013",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/hondabike.jpeg",
  },
  {
    price: "$ 78,000",
    eco: "75/100",
    km: "2014-75,000km",
    model: "Royal Enfield Meteor 350",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/royanenfieldbike.jpg",
  },
];
const recommendedItem = [
  {
    price: "$ 35,000",
    eco: "82/100",
    year: "2019",
    model: "iPhone 12, 2029",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/iphone.jpg",
  },
  {
    price: "$ 18,000",
    eco: "82/100",
    year: "2018",
    model: "Blue Refrigerator",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/fridge.jpg",
  },
  {
    price: "$ 5,000",
    eco: "82/100",
    year: "2024",
    model: "Paint Brushes",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/colors.jpg",
  },
  {
    price: "$ 1,500",
    eco: "82/100",
    year: "100% Cotton",
    model: "White and blue combo outfit",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/clothes.jpg",
  },
  {
    price: "$ 1,100",
    eco: "82/100",
    year: "Best quality",
    model: "Sneakers",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/shoes.jpg",
  },
  {
    price: "$ 1,000",
    eco: "82/100",
    year: "2017",
    model: "LED smart tv",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/tv.jpg",
  },
  {
    price: "$ 55,000",
    eco: "82/100",
    year: "2022",
    model: "HP laptop",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/laptop.jpg",
  },
  {
    price: "$ 500",
    eco: "82/100",
    year: "2023",
    model: "A wooden chair for work",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/chair.jpg",
  },
];

const pagerecommendedItem = [
  {
    price: "$ 35,000",
    eco: "82/100",
    year: "2019",
    model: "iPhone 12, 2029",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/iphone.jpg",
  },
  {
    price: "$ 18,000",
    eco: "82/100",
    year: "2018",
    model: "Blue Refrigerator",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/fridge.jpg",
  },
  {
    price: "$ 5,000",
    eco: "82/100",
    year: "2024",
    model: "Paint Brushes",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/colors.jpg",
  },
  {
    price: "$ 500",
    eco: "82/100",
    year: "2023",
    model: "A wooden chair for work",
    location: "Bengaluru",
    date: "Today",
    bannerImg: "/chair.jpg",
  },
];

export {
  recSearches,
  newlistedCar,
  newlistedBike,
  newcarDetail,
  newbikeDetail,
  recommendedItem,
  pagerecommendedItem,
};
